"""add client_email_id to get_invoice

Revision ID: 1aaba0d1fa0d
Revises: 927f35fffe02
Create Date: 2026-03-01 12:06:37.188725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1aaba0d1fa0d'
down_revision: Union[str, None] = '927f35fffe02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('get_invoice', sa.Column('client_email_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('get_invoice', 'client_email_id')
    # ### end Alembic commands ###
