"""add gst_number to client

Revision ID: 33cdbd9654a2
Revises: 0dcc43f8c60d
Create Date: 2025-12-30 16:29:25.039944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33cdbd9654a2'
down_revision: Union[str, None] = '0dcc43f8c60d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('gst_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'gst_number')
    # ### end Alembic commands ###
