"""Add get_invoice table

Revision ID: a049284ba33e
Revises: f25ea10706f6
Create Date: 2026-02-28 13:48:12.279513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a049284ba33e'
down_revision: Union[str, None] = 'f25ea10706f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('get_invoice',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('gst_number', sa.String(length=50), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('invoice_date', sa.DateTime(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('gst_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('expenses_type', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('get_invoice')
    # ### end Alembic commands ###
