"""add_accounting_vouchers_and_invoice_filepath

Revision ID: c9f66007637c
Revises: 52a7aa767586
Create Date: 2026-03-01 15:23:46.751709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9f66007637c'
down_revision: Union[str, None] = '52a7aa767586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting_vouchers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('voucher_type', sa.String(length=50), nullable=False),
    sa.Column('supplier_invoice_no', sa.String(length=100), nullable=True),
    sa.Column('voucher_date', sa.DateTime(), nullable=True),
    sa.Column('party_name', sa.String(length=255), nullable=False),
    sa.Column('gst_number', sa.String(length=50), nullable=True),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('sub_total', sa.String(length=50), nullable=True),
    sa.Column('tax_amount', sa.String(length=50), nullable=True),
    sa.Column('total_amount', sa.String(length=50), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=True),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voucher_ledger_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('voucher_id', sa.UUID(), nullable=False),
    sa.Column('ledger_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['voucher_id'], ['accounting_vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voucher_tax_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('voucher_id', sa.UUID(), nullable=False),
    sa.Column('ledger_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['voucher_id'], ['accounting_vouchers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('get_invoice', sa.Column('file_path', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('get_invoice', 'file_path')
    op.drop_table('voucher_tax_items')
    op.drop_table('voucher_ledger_items')
    op.drop_table('accounting_vouchers')
    # ### end Alembic commands ###

