"""Add email to Client

Revision ID: f25ea10706f6
Revises: 09508c52aa37
Create Date: 2026-02-28 13:45:34.749339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f25ea10706f6'
down_revision: Union[str, None] = '09508c52aa37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('email', sa.String(length=255), server_default='admin@example.com', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'email')
    # ### end Alembic commands ###
