"""
Seed script — Agreement Categories, Types & Default Clause Templates
Run: cd apps/api && ../../venv/bin/python -m seed_agreements
"""
import asyncio
import uuid
import json

from app.db.session import AsyncSessionLocal
from app.models.agreements import AgreementCategory, AgreementType


# ─── Helper ───
def C(id, title, content, is_default=True, order=0):
    return {"id": id, "title": title, "content": content, "is_default": is_default, "order": order}


# ════════════════════════════════════════
#  CATEGORIES  +  AGREEMENT TYPES
# ════════════════════════════════════════

SEED_DATA = [
    # ── 1. Business & Partnership ──
    {
        "name": "Business & Partnership",
        "description": "Agreements governing business formation, partnerships, and joint ventures",
        "icon": "🏢",
        "order": 1,
        "types": [
            {
                "name": "Partnership Deed",
                "description": "Agreement between partners defining terms of a partnership firm under the Indian Partnership Act, 1932",
                "icon": "🤝",
                "clauses": [
                    C("pd_1", "Name & Nature of Business", "The partnership firm shall be carried on under the name and style of \"[FIRM NAME]\" and the nature of business shall be [DESCRIPTION].", True, 1),
                    C("pd_2", "Commencement & Duration", "The partnership shall commence from [DATE] and shall continue until dissolved by mutual consent of all partners or as provided herein.", True, 2),
                    C("pd_3", "Capital Contribution", "The partners shall contribute capital as follows:\n- Partner A: ₹[AMOUNT]\n- Partner B: ₹[AMOUNT]\nInterest on capital shall be allowed at [X]% per annum.", True, 3),
                    C("pd_4", "Profit & Loss Sharing", "The net profits and losses of the firm shall be shared among the partners in the following ratio:\n- Partner A: [X]%\n- Partner B: [Y]%", True, 4),
                    C("pd_5", "Duties & Obligations", "Each partner shall devote their full time and attention to the business and shall not engage in any competing business without prior written consent of the other partners.", True, 5),
                    C("pd_6", "Banking & Financial Operations", "The firm shall maintain bank accounts with [BANK NAME]. All cheques, instruments, and banking transactions above ₹[AMOUNT] shall require joint signatures of at least two partners.", True, 6),
                    C("pd_7", "Books of Accounts & Audit", "Proper books of accounts shall be maintained at the principal place of business and shall be audited annually by a Chartered Accountant as required under the Income Tax Act, 1961.", True, 7),
                    C("pd_8", "Admission of New Partner", "No new partner shall be admitted without the unanimous written consent of all existing partners.", False, 8),
                    C("pd_9", "Retirement & Expulsion", "A partner may retire from the firm by giving [X] months' written notice. A partner may be expelled by a majority decision for breach of terms, subject to the provisions of Section 33 of the Indian Partnership Act, 1932.", False, 9),
                    C("pd_10", "Dissolution", "The firm may be dissolved by mutual consent, by notice, or by order of the Court as per Sections 40-44 of the Indian Partnership Act, 1932. Upon dissolution, the assets shall be applied first to pay debts and liabilities, and the surplus shall be distributed as per capital contributions.", True, 10),
                    C("pd_11", "Arbitration", "Any dispute arising between the partners shall be referred to arbitration in accordance with the Arbitration and Conciliation Act, 1996.", True, 11),
                    C("pd_12", "Jurisdiction", "This deed shall be governed by the laws of India and the courts at [CITY] shall have exclusive jurisdiction.", True, 12),
                ],
            },
            {
                "name": "LLP Agreement",
                "description": "Agreement for a Limited Liability Partnership under the LLP Act, 2008",
                "icon": "📋",
                "template_path": "business_and_partnership/LLP_Agreement_Template.docx",
                "clauses": [
                    C("llp_1", "Name & Registered Office", "The LLP shall be known as \"[LLP NAME] LLP\" with its registered office at [ADDRESS].", True, 1),
                    C("llp_2", "Designated Partners", "The designated partners of the LLP shall be:\n1. [NAME] — DIN: [NUMBER]\n2. [NAME] — DIN: [NUMBER]\nAt least two designated partners shall be individuals and at least one shall be a resident of India as per Section 7 of the LLP Act, 2008.", True, 2),
                    C("llp_3", "Capital Contribution", "Each partner shall contribute to the LLP as follows:\n- Partner A: ₹[AMOUNT]\n- Partner B: ₹[AMOUNT]\nFurther contributions may be made as mutually agreed.", True, 3),
                    C("llp_4", "Profit Sharing Ratio", "Profits and losses shall be shared among the partners in the ratio of [X:Y], unless otherwise agreed in writing.", True, 4),
                    C("llp_5", "Management & Decision Making", "Day-to-day management shall be vested in the designated partners. Decisions on matters involving expenditure exceeding ₹[AMOUNT] shall require consent of all partners.", True, 5),
                    C("llp_6", "Rights & Duties of Partners", "Every partner has the right to take part in the conduct of business, inspect books, and share in profits. No partner shall carry on competing business.", True, 6),
                    C("llp_7", "Books of Accounts", "Books of accounts shall be maintained on accrual basis and audited as per Section 34 of the LLP Act, 2008, if turnover exceeds ₹40 lakhs or contribution exceeds ₹25 lakhs.", True, 7),
                    C("llp_8", "Transfer of Partnership Interest", "No partner shall transfer their interest without the prior written consent of all other partners.", False, 8),
                    C("llp_9", "Winding Up", "The LLP may be wound up voluntarily or by the Tribunal as per Chapter XI of the LLP Act, 2008.", True, 9),
                    C("llp_10", "Dispute Resolution", "Disputes shall be settled by arbitration under the Arbitration and Conciliation Act, 1996, with the seat at [CITY].", True, 10),
                ],
            },
            {
                "name": "Joint Venture Agreement",
                "description": "Agreement between parties for a specific business venture or project",
                "icon": "🔗",
                "clauses": [
                    C("jv_1", "Parties & Recitals", "This Joint Venture Agreement is entered into between [PARTY A] and [PARTY B] (hereinafter collectively referred to as 'Venturers') for the purpose of [PROJECT DESCRIPTION].", True, 1),
                    C("jv_2", "Scope & Purpose", "The Joint Venture is formed for the specific purpose of [DESCRIBE VENTURE]. The scope shall not be expanded without mutual written consent.", True, 2),
                    C("jv_3", "Contributions", "Party A shall contribute [DESCRIBE — capital/assets/expertise] valued at ₹[AMOUNT].\nParty B shall contribute [DESCRIBE] valued at ₹[AMOUNT].", True, 3),
                    C("jv_4", "Profit & Loss Sharing", "Profits and losses from the venture shall be shared in the ratio of [X:Y] between the parties.", True, 4),
                    C("jv_5", "Management & Control", "A Joint Venture Committee of [N] members shall oversee operations. Each party shall nominate [N] representatives.", True, 5),
                    C("jv_6", "Duration & Termination", "This JV shall remain in effect from [START DATE] until completion of the venture or [END DATE], whichever is earlier. Either party may terminate with [X] days' written notice for material breach.", True, 6),
                    C("jv_7", "Intellectual Property", "All IP created during the venture shall be jointly owned unless otherwise agreed.", False, 7),
                    C("jv_8", "Confidentiality", "Both parties shall maintain strict confidentiality of all proprietary information exchanged during the course of this venture.", True, 8),
                    C("jv_9", "Non-Compete", "During the term and for [X] months after termination, neither party shall engage in competing activities within [GEOGRAPHIC AREA].", False, 9),
                    C("jv_10", "Governing Law", "This Agreement shall be governed by Indian law and disputes shall be subject to jurisdiction of courts at [CITY].", True, 10),
                ],
            },
            {
                "name": "Shareholders Agreement",
                "description": "Agreement between shareholders of a private limited company",
                "icon": "📊",
                "clauses": [
                    C("sha_1", "Parties & Company Details", "This Shareholders Agreement is between the shareholders of [COMPANY NAME] (CIN: [NUMBER]), incorporated under the Companies Act, 2013.", True, 1),
                    C("sha_2", "Share Capital & Ownership", "The authorized share capital is ₹[AMOUNT] divided into [N] equity shares of ₹[FACE VALUE] each. The shareholding pattern is:\n- Shareholder A: [X]%\n- Shareholder B: [Y]%", True, 2),
                    C("sha_3", "Board Composition", "The Board shall consist of [N] directors. Shareholder A shall nominate [N] directors and Shareholder B shall nominate [N] directors.", True, 3),
                    C("sha_4", "Reserved Matters", "The following matters shall require unanimous consent:\n- Alteration of share capital\n- Issue of new shares\n- Merger, acquisition, or demerger\n- Borrowings exceeding ₹[AMOUNT]\n- Related party transactions", True, 4),
                    C("sha_5", "Transfer Restrictions & Right of First Refusal", "No shareholder shall transfer shares without first offering them to existing shareholders at fair market value as determined by the company's auditor.", True, 5),
                    C("sha_6", "Tag-Along & Drag-Along Rights", "Tag-Along: Minority shareholders may participate in any sale by majority shareholders on the same terms.\nDrag-Along: Majority shareholders holding [X]% may compel minority to sell on the same terms.", False, 6),
                    C("sha_7", "Anti-Dilution Protection", "In the event of new share issuance, existing shareholders shall have proportionate pre-emptive rights to maintain their ownership percentage.", False, 7),
                    C("sha_8", "Dividend Policy", "The company shall declare dividends as recommended by the Board, subject to availability of profits and compliance with Section 123 of the Companies Act, 2013.", True, 8),
                    C("sha_9", "Non-Compete & Non-Solicitation", "During shareholding and for [X] years after exit, shareholders shall not engage in competing business or solicit employees/clients of the Company.", False, 9),
                    C("sha_10", "Exit Mechanisms", "Exit may be through IPO, strategic sale, buyback, or mutual agreement. A deadlock resolution mechanism shall apply in case of irreconcilable disputes.", True, 10),
                ],
            },
            {
                "name": "Memorandum of Understanding (MOU)",
                "description": "Preliminary understanding between parties before a formal agreement",
                "icon": "📝",
                "template_path": "business_and_partnership/MOU_India.docx",
                "template_fields": [
                    {"name": "party_a_name", "type": "text", "label": "First Party Name", "required": True},
                    {"name": "party_a_address", "type": "textarea", "label": "First Party Address", "required": True},
                    {"name": "party_a_business", "type": "text", "label": "First Party Business Area", "required": True},
                    {"name": "party_b_business", "type": "text", "label": "Second Party Business Area", "required": True},
                    {"name": "collaboration_field", "type": "text", "label": "Field of Collaboration", "required": True},
                    {"name": "mou_purpose", "type": "textarea", "label": "Purpose of MOU", "required": True},
                    {"name": "effective_date", "type": "date", "label": "Effective Date", "required": True},
                    {"name": "valid_months", "type": "number", "label": "Valid For (Months)", "required": True},
                    {"name": "party_a_responsibility_1", "type": "text", "label": "Party A Responsibility 1", "required": True},
                    {"name": "party_a_responsibility_2", "type": "text", "label": "Party A Responsibility 2", "required": False},
                    {"name": "party_a_responsibility_3", "type": "text", "label": "Party A Responsibility 3", "required": False},
                    {"name": "party_b_responsibility_1", "type": "text", "label": "Party B Responsibility 1", "required": True},
                    {"name": "party_b_responsibility_2", "type": "text", "label": "Party B Responsibility 2", "required": False},
                    {"name": "party_b_responsibility_3", "type": "text", "label": "Party B Responsibility 3", "required": False},
                    {"name": "confidentiality_years", "type": "number", "label": "Confidentiality Duration (Years)", "required": True},
                    {"name": "jurisdiction_city", "type": "text", "label": "Jurisdiction City", "required": True},
                    {"name": "num_originals", "type": "number", "label": "Number of Originals", "required": True},
                ],
                "clauses": [
                    C("mou_1", "Parties", "This MOU is between [PARTY A] and [PARTY B] to record their mutual understanding regarding [SUBJECT].", True, 1),
                    C("mou_2", "Background & Purpose", "The parties wish to explore a potential collaboration for [DESCRIBE PURPOSE]. This MOU records the preliminary understanding and framework.", True, 2),
                    C("mou_3", "Scope of Collaboration", "The parties shall collaborate on [SPECIFIC AREAS], share resources, and work towards [STATED GOAL].", True, 3),
                    C("mou_4", "Roles & Responsibilities", "Party A shall be responsible for [DESCRIBE].\nParty B shall be responsible for [DESCRIBE].", True, 4),
                    C("mou_5", "Timeline", "The parties intend to execute a definitive agreement within [X] days from the date of this MOU.", True, 5),
                    C("mou_6", "Confidentiality", "All information exchanged during the course of discussions shall be treated as confidential.", True, 6),
                    C("mou_7", "Non-Binding Nature", "This MOU is a statement of intent and is not legally binding, except for the clauses on Confidentiality and Governing Law.", True, 7),
                    C("mou_8", "Expenses", "Each party shall bear its own costs and expenses incurred in relation to the negotiations under this MOU.", False, 8),
                    C("mou_9", "Governing Law", "This MOU shall be governed by Indian law.", True, 9),
                ],
            },
        ],
    },

    # ── 2. Service & Professional ──
    {
        "name": "Service & Professional",
        "description": "Agreements for professional services, consultancy, and business relationships",
        "icon": "💼",
        "order": 2,
        "types": [
            {
                "name": "Service Agreement",
                "description": "General agreement for provision of services between a service provider and client",
                "icon": "🛠️",
                "template_path": "service_and_professionals/Service_Agreement_India.docx",
                "template_fields": [
                    {"name": "execution_day", "type": "number", "label": "Execution Day (e.g., 15)", "required": True},
                    {"name": "execution_month", "type": "text", "label": "Execution Month (e.g., October)", "required": True},
                    {"name": "execution_year", "type": "number", "label": "Execution Year (e.g., 2024)", "required": True},
                    {"name": "execution_city", "type": "text", "label": "Execution City", "required": True},
                    {"name": "client_name", "type": "text", "label": "Client Name", "required": True},
                    {"name": "client_address", "type": "textarea", "label": "Client Address", "required": True},
                    {"name": "provider_name", "type": "text", "label": "Service Provider Name", "required": True},
                    {"name": "provider_address", "type": "textarea", "label": "Service Provider Address", "required": True},
                    {"name": "service_1", "type": "textarea", "label": "Service 1 Description", "required": True},
                    {"name": "service_2", "type": "textarea", "label": "Service 2 Description", "required": False},
                    {"name": "service_3", "type": "textarea", "label": "Service 3 Description", "required": False},
                    {"name": "start_date", "type": "date", "label": "Start Date", "required": True},
                    {"name": "end_date", "type": "date", "label": "End Date", "required": True},
                    {"name": "fee_amount_numbers", "type": "number", "label": "Total Fee (₹)", "required": True},
                    {"name": "fee_amount_words", "type": "text", "label": "Fee in Words", "required": True},
                    {"name": "advance_pct", "type": "number", "label": "Advance %", "required": True},
                    {"name": "final_pct", "type": "number", "label": "Final %", "required": True},
                    {"name": "invoice_days", "type": "number", "label": "Invoice Payment terms (Days)", "required": True},
                    {"name": "interest_pct", "type": "number", "label": "Late Payment Interest %", "required": True},
                    {"name": "out_of_pocket_details", "type": "textarea", "label": "Reimbursable Expenses Limit/Details", "required": True},
                    {"name": "review_days", "type": "number", "label": "Deliverable Review Days", "required": True},
                    {"name": "resubmit_days", "type": "number", "label": "Deliverable Resubmit Days", "required": True},
                    {"name": "confidentiality_survive_years", "type": "number", "label": "Confidentiality Survival (Years)", "required": True},
                    {"name": "termination_notice_days", "type": "number", "label": "Termination Notice (Days)", "required": True},
                    {"name": "cure_period_days", "type": "number", "label": "Breach Cure Period (Days)", "required": True},
                    {"name": "arbitration_city", "type": "text", "label": "Arbitration City", "required": True},
                    {"name": "courts_city", "type": "text", "label": "Jurisdiction Courts City", "required": True},
                    {"name": "num_originals", "type": "number", "label": "Number of Originals", "required": True},
                ],
                "clauses": [
                    C("sa_1", "Parties & Engagement", "This Service Agreement is between [SERVICE PROVIDER] and [CLIENT]. The Service Provider agrees to provide [DESCRIBE SERVICES].", True, 1),
                    C("sa_2", "Scope of Services", "The services to be provided include:\n1. [SERVICE 1]\n2. [SERVICE 2]\n3. [SERVICE 3]\nAny additional services shall be governed by a separate work order.", True, 2),
                    C("sa_3", "Term & Renewal", "This Agreement shall be effective from [START DATE] for a period of [X] months/years. It may be renewed upon mutual written consent [X] days prior to expiry.", True, 3),
                    C("sa_4", "Compensation & Payment Terms", "The Client shall pay the Service Provider ₹[AMOUNT] [per month/per milestone/lump sum]. GST as applicable shall be charged additionally. Payment shall be due within [X] days of invoice.", True, 4),
                    C("sa_5", "Service Level Standards", "The Service Provider shall maintain [DESCRIBE STANDARDS]. Performance shall be reviewed [monthly/quarterly].", True, 5),
                    C("sa_6", "Intellectual Property", "All deliverables created under this Agreement shall be the property of [CLIENT/SERVICE PROVIDER] upon full payment.", True, 6),
                    C("sa_7", "Confidentiality", "Both parties shall maintain confidentiality of proprietary information for the term and [X] years after termination.", True, 7),
                    C("sa_8", "Limitation of Liability", "The Service Provider's total liability under this Agreement shall not exceed the total fees paid in the preceding [X] months.", False, 8),
                    C("sa_9", "Termination", "Either party may terminate with [X] days' written notice. Termination for cause is effective immediately upon written notice of material breach.", True, 9),
                    C("sa_10", "Force Majeure", "Neither party shall be liable for failure to perform due to events beyond reasonable control, including natural disaster, pandemic, government action, etc.", False, 10),
                    C("sa_11", "Dispute Resolution", "Disputes shall first be attempted to be resolved through mediation, failing which by arbitration under the Arbitration and Conciliation Act, 1996.", True, 11),
                ],
            },
            {
                "name": "Consultancy Agreement",
                "description": "Agreement between a consultant and a company for advisory services",
                "icon": "🎯",
                "clauses": [
                    C("ca_1", "Engagement of Consultant", "The Company hereby engages [CONSULTANT NAME] as an independent consultant to provide advisory services in [AREA OF EXPERTISE].", True, 1),
                    C("ca_2", "Scope of Consultancy", "The Consultant shall provide:\n- Strategic advisory on [AREAS]\n- Reports and recommendations\n- Attendance at meetings as required", True, 2),
                    C("ca_3", "Fees & Reimbursement", "The Consultant shall be paid ₹[AMOUNT] per [month/project]. Travel and out-of-pocket expenses shall be reimbursed at actuals with prior approval.", True, 3),
                    C("ca_4", "Independent Contractor", "The Consultant is an independent contractor and not an employee. No employment benefits, PF, or ESI shall be applicable.", True, 4),
                    C("ca_5", "Deliverables & Timeline", "The Consultant shall deliver [DESCRIBE DELIVERABLES] within [TIMELINE].", True, 5),
                    C("ca_6", "Confidentiality & Non-Disclosure", "The Consultant shall not disclose any confidential information of the Company during or after the engagement.", True, 6),
                    C("ca_7", "Non-Solicitation", "The Consultant shall not solicit employees or clients of the Company for [X] months after the engagement ends.", False, 7),
                    C("ca_8", "Termination", "Either party may terminate with [X] days' written notice. Outstanding fees shall be settled within [X] days of termination.", True, 8),
                    C("ca_9", "Indemnification", "The Consultant shall indemnify the Company against losses arising from negligence or breach of this Agreement.", False, 9),
                    C("ca_10", "Governing Law", "Governed by Indian law. Courts at [CITY] shall have jurisdiction.", True, 10),
                ],
            },
            {
                "name": "Non-Disclosure Agreement (NDA)",
                "description": "Agreement to protect confidential information shared between parties",
                "icon": "🔒",
                "clauses": [
                    C("nda_1", "Parties", "This NDA is between [DISCLOSING PARTY] and [RECEIVING PARTY].", True, 1),
                    C("nda_2", "Definition of Confidential Information", "\"Confidential Information\" includes all non-public information disclosed by either party, including business plans, financial data, client lists, proprietary technology, trade secrets, and any information marked as confidential.", True, 2),
                    C("nda_3", "Obligations of Receiving Party", "The Receiving Party shall:\n- Use Confidential Information solely for the stated purpose\n- Restrict disclosure to employees/agents on a need-to-know basis\n- Apply the same degree of care as for its own confidential information", True, 3),
                    C("nda_4", "Exclusions", "Confidential Information does not include information that: (a) is publicly available; (b) was known prior to disclosure; (c) is independently developed; (d) is disclosed by a third party without restriction.", True, 4),
                    C("nda_5", "Term of Confidentiality", "The obligations under this NDA shall survive for [X] years from the date of disclosure.", True, 5),
                    C("nda_6", "Return of Information", "Upon request or termination, the Receiving Party shall return or destroy all copies of Confidential Information.", True, 6),
                    C("nda_7", "Remedies", "The Disclosing Party shall be entitled to seek injunctive relief for breach, in addition to damages.", True, 7),
                    C("nda_8", "Non-Circumvention", "Neither party shall circumvent the other to deal directly with contacts introduced during the course of discussions.", False, 8),
                    C("nda_9", "Governing Law & Jurisdiction", "Governed by Indian law. Courts at [CITY] shall have exclusive jurisdiction.", True, 9),
                ],
            },
            {
                "name": "Retainer Agreement",
                "description": "Ongoing professional engagement with periodic retainer fees",
                "icon": "🔄",
                "template_path": "service_and_professionals/Retainer_Agreement_India.docx",
                "clauses": [
                    C("ret_1", "Engagement", "The Client retains [PROFESSIONAL/FIRM] for ongoing advisory on [AREAS] commencing [DATE].", True, 1),
                    C("ret_2", "Scope of Retainer Services", "Services include:\n- Periodic advisory and consultations\n- Review of documents as submitted\n- Telephonic/virtual guidance\n- [X] hours of service per month", True, 2),
                    C("ret_3", "Retainer Fee", "Monthly retainer of ₹[AMOUNT] + GST, payable by [DATE] of each month. Unused hours do not carry forward.", True, 3),
                    C("ret_4", "Additional Services", "Services beyond the retainer scope shall be charged at ₹[RATE] per hour with prior approval.", True, 4),
                    C("ret_5", "Term & Renewal", "Initial term of [X] months, auto-renewing unless either party provides [X] days' written notice.", True, 5),
                    C("ret_6", "Confidentiality", "Both parties shall maintain confidentiality of information exchanged.", True, 6),
                    C("ret_7", "Termination", "Either party may terminate with [X] days' prior written notice. Outstanding fees remain payable.", True, 7),
                    C("ret_8", "Limitation of Liability", "Total liability shall not exceed [X] months' retainer fees.", False, 8),
                ],
            },
            {
                "name": "Service Level Agreement (SLA)",
                "description": "Agreement defining service quality metrics, responsibilities, and remedies",
                "icon": "📈",
                "clauses": [
                    C("sla_1", "Parties & Service Description", "This SLA is between [SERVICE PROVIDER] and [CLIENT] for the provision of [SERVICES].", True, 1),
                    C("sla_2", "Service Levels & KPIs", "The following service levels shall be maintained:\n- Uptime: [X]%\n- Response Time: [X] hours\n- Resolution Time: [X] hours\n- Quality Score: [X]%", True, 2),
                    C("sla_3", "Monitoring & Reporting", "Performance shall be monitored and reported [weekly/monthly] with detailed metrics dashboard.", True, 3),
                    C("sla_4", "Penalties & Credits", "If service levels are not met:\n- [X]% credit for each [Y]% shortfall in uptime\n- Maximum credit: [X]% of monthly fees", True, 4),
                    C("sla_5", "Escalation Procedure", "Level 1: Service desk — [X] hours\nLevel 2: Service Manager — [X] hours\nLevel 3: Senior Management — [X] hours", True, 5),
                    C("sla_6", "Exclusions", "SLA metrics exclude downtime due to scheduled maintenance, force majeure, or client-caused issues.", True, 6),
                    C("sla_7", "Review & Amendments", "This SLA shall be reviewed [quarterly/annually] and may be amended by mutual written agreement.", True, 7),
                ],
            },
        ],
    },

    # ── 3. Employment & HR ──
    {
        "name": "Employment & HR",
        "description": "Agreements governing employment relationships, terms of service, and HR policies",
        "icon": "👥",
        "order": 3,
        "types": [
            {
                "name": "Employment Agreement",
                "description": "Comprehensive employment contract covering terms and conditions of service",
                "icon": "📄",
                "clauses": [
                    C("emp_1", "Appointment", "The Company hereby appoints [EMPLOYEE NAME] as [DESIGNATION] in the [DEPARTMENT] effective from [DATE].", True, 1),
                    C("emp_2", "Probation Period", "The Employee shall be on probation for a period of [X] months from the date of joining. The Company may extend probation or terminate during this period with [X] days' notice.", True, 2),
                    C("emp_3", "Compensation & Benefits", "Annual CTC: ₹[AMOUNT]\nBreakup:\n- Basic Salary: ₹[AMOUNT]\n- HRA: ₹[AMOUNT]\n- Special Allowance: ₹[AMOUNT]\n- PF (Employer): ₹[AMOUNT]\nBenefits include [health insurance/leaves/etc.].", True, 3),
                    C("emp_4", "Working Hours & Location", "Standard working hours: [X] hours/day, [X] days/week. Place of work: [LOCATION]. The Company may transfer the Employee to another location with reasonable notice.", True, 4),
                    C("emp_5", "Leave Policy", "The Employee shall be entitled to:\n- Casual Leave: [X] days\n- Sick Leave: [X] days\n- Privilege/Earned Leave: [X] days\n- Public Holidays as per Company policy", True, 5),
                    C("emp_6", "Duties & Responsibilities", "The Employee shall faithfully perform duties as assigned, comply with Company policies, and report to [REPORTING MANAGER].", True, 6),
                    C("emp_7", "Confidentiality", "The Employee shall not disclose any trade secrets, client data, or proprietary information of the Company during or after employment.", True, 7),
                    C("emp_8", "Non-Compete", "For [X] months after separation, the Employee shall not join or establish any competing business within [GEOGRAPHIC SCOPE].", False, 8),
                    C("emp_9", "Intellectual Property Assignment", "All inventions, works, and IP created during employment shall be the exclusive property of the Company.", True, 9),
                    C("emp_10", "Termination", "Either party may terminate with [X] months' written notice or salary in lieu thereof. The Company may terminate without notice for misconduct as defined herein.", True, 10),
                    C("emp_11", "Gratuity", "Gratuity shall be payable as per the Payment of Gratuity Act, 1972, for employees completing 5 years of continuous service.", False, 11),
                    C("emp_12", "Governing Law", "This Agreement is governed by Indian law. Labour laws and courts at [CITY] shall apply.", True, 12),
                ],
            },
            {
                "name": "Offer Letter",
                "description": "Formal offer of employment with key terms",
                "icon": "✉️",
                "template_path": "employment_and_hr/Offer_Letter_India.docx",
                "template_fields": [
                    {"name": "ref_no", "type": "text", "label": "Reference Number", "required": True},
                    {"name": "offer_date", "type": "date", "label": "Offer Date", "required": True},
                    {"name": "employee_name", "type": "text", "label": "Employee Name", "required": True},
                    {"name": "employee_father_name", "type": "text", "label": "Employee Father's Name", "required": True},
                    {"name": "employee_address", "type": "textarea", "label": "Employee Address", "required": True},
                    {"name": "position_title", "type": "text", "label": "Position Title", "required": True},
                    {"name": "employee_name_salutation", "type": "text", "label": "Employee Name (with salutation)", "required": True},
                    {"name": "company_name", "type": "text", "label": "Company Name", "required": True},
                    {"name": "designation", "type": "text", "label": "Designation", "required": True},
                    {"name": "department", "type": "text", "label": "Department", "required": True},
                    {"name": "reporting_to", "type": "text", "label": "Reporting To", "required": True},
                    {"name": "posting_location", "type": "text", "label": "Posting Location", "required": True},
                    {"name": "joining_date", "type": "date", "label": "Joining Date", "required": True},
                    {"name": "ctc_numbers", "type": "number", "label": "CTC per annum (₹)", "required": True},
                    {"name": "ctc_words", "type": "text", "label": "CTC in Words", "required": True},
                    {"name": "salary_credit_day", "type": "number", "label": "Salary Credit Day (e.g., 7th)", "required": True},
                    {"name": "probation_months", "type": "number", "label": "Probation Period (Months)", "required": True},
                    {"name": "hours_per_day", "type": "number", "label": "Working Hours per Day", "required": True},
                    {"name": "days_per_week", "type": "number", "label": "Working Days per Week", "required": True},
                    {"name": "notice_period_months", "type": "number", "label": "Notice Period (Months)", "required": True},
                    {"name": "non_compete_months", "type": "number", "label": "Non-Compete Period (Months)", "required": True},
                    {"name": "governing_state", "type": "text", "label": "Governing State", "required": True},
                    {"name": "acceptance_days", "type": "number", "label": "Acceptance Deadline (Days)", "required": True},
                    {"name": "hr_name", "type": "text", "label": "HR Signatory Name", "required": True},
                    {"name": "hr_designation", "type": "text", "label": "HR Signatory Designation", "required": True},
                    {"name": "company_name_footer", "type": "text", "label": "Company Name Footer", "required": True},
                    {"name": "employee_name_accepting", "type": "text", "label": "Employee Name Accepting", "required": True},
                    {"name": "employee_signature", "type": "text", "label": "Employee Signature Place", "required": True},
                    {"name": "date_signed", "type": "date", "label": "Date Signed", "required": True},
                    {"name": "employee_name_footer", "type": "text", "label": "Employee Name Footer", "required": True},
                    {"name": "pan_number", "type": "text", "label": "PAN Number", "required": True},
                ],
                "clauses": [
                    C("ol_1", "Offer of Employment", "We are pleased to offer you the position of [DESIGNATION] at [COMPANY NAME], subject to the terms outlined herein.", True, 1),
                    C("ol_2", "Date of Joining", "Your date of joining shall be [DATE]. Please report to [LOCATION] at [TIME].", True, 2),
                    C("ol_3", "Compensation", "Your annual CTC shall be ₹[AMOUNT]. Detailed compensation breakup is enclosed as Annexure A.", True, 3),
                    C("ol_4", "Reporting & Designation", "You shall report to [MANAGER NAME/TITLE] and your designation shall be [TITLE].", True, 4),
                    C("ol_5", "Documents Required", "Please carry the following documents on your date of joining:\n- PAN Card\n- Aadhaar Card\n- Educational certificates\n- Previous employment relieving letter\n- Passport-size photographs", True, 5),
                    C("ol_6", "Background Verification", "This offer is subject to satisfactory completion of background verification.", True, 6),
                    C("ol_7", "Acceptance", "Please sign and return this offer letter by [DATE] to confirm your acceptance.", True, 7),
                ],
            },
            {
                "name": "Non-Compete Agreement",
                "description": "Restrictive covenant preventing competition during and after employment",
                "icon": "⛔",
                "clauses": [
                    C("nc_1", "Recitals", "WHEREAS the Employee has access to confidential business information and trade secrets, the parties agree to the following restrictive covenant.", True, 1),
                    C("nc_2", "Non-Compete Obligation", "During employment and for [X] months thereafter, the Employee shall not directly or indirectly engage in, own, manage, or be employed by any business that competes with the Company in [INDUSTRY/GEOGRAPHY].", True, 2),
                    C("nc_3", "Non-Solicitation of Clients", "The Employee shall not solicit, canvass, or approach any client or prospective client of the Company for [X] months after separation.", True, 3),
                    C("nc_4", "Non-Solicitation of Employees", "The Employee shall not recruit or attempt to recruit any employee of the Company for [X] months after separation.", True, 4),
                    C("nc_5", "Consideration", "In consideration of this Agreement, the Company agrees to [DESCRIBE — continued employment/bonus/compensation].", True, 5),
                    C("nc_6", "Remedies", "The Company shall be entitled to injunctive relief and damages for breach of this Agreement.", True, 6),
                    C("nc_7", "Severability", "If any clause is held unenforceable, it shall be modified to the minimum extent necessary. Note: Indian courts may not enforce post-employment non-compete clauses under Section 27 of the Indian Contract Act, 1872, but non-solicitation is generally upheld.", True, 7),
                ],
            },
            {
                "name": "Confidentiality Agreement (Employee)",
                "description": "Employee confidentiality and IP assignment agreement",
                "icon": "🔐",
                "clauses": [
                    C("econf_1", "Scope of Confidential Information", "All information relating to Company's business including client lists, financial data, strategies, software, algorithms, and processes shall be treated as confidential.", True, 1),
                    C("econf_2", "Obligations", "The Employee shall:\n- Not disclose confidential information to third parties\n- Use it solely for Company business\n- Take reasonable safeguards to prevent unauthorized disclosure", True, 2),
                    C("econf_3", "IP Assignment", "All work product, inventions, and improvements created during employment belong to the Company.", True, 3),
                    C("econf_4", "Return of Materials", "Upon separation, the Employee shall return all Company property, documents, devices, and data.", True, 4),
                    C("econf_5", "Survival", "Confidentiality obligations survive termination of employment for [X] years.", True, 5),
                    C("econf_6", "Remedies", "Breach shall entitle the Company to injunctive relief, damages, and recovery of legal costs.", True, 6),
                ],
            },
            {
                "name": "Internship Agreement",
                "description": "Agreement for internship engagement with educational institutions or individuals",
                "icon": "🎓",
                "clauses": [
                    C("int_1", "Engagement", "The Company engages [INTERN NAME] as an intern in the [DEPARTMENT] from [START DATE] to [END DATE].", True, 1),
                    C("int_2", "Stipend", "The intern shall receive a monthly stipend of ₹[AMOUNT]. This is not a salary and does not create an employer-employee relationship.", True, 2),
                    C("int_3", "Working Hours", "The intern shall work [X] hours per day, [X] days per week.", True, 3),
                    C("int_4", "Scope of Work", "The intern shall assist with [DESCRIBE TASKS] under the supervision of [MENTOR NAME].", True, 4),
                    C("int_5", "Confidentiality", "The intern shall maintain confidentiality of all Company information during and after the internship.", True, 5),
                    C("int_6", "Certificate", "Upon satisfactory completion, the Company shall issue an internship completion certificate.", True, 6),
                    C("int_7", "No Employment Guarantee", "This internship does not guarantee future employment with the Company.", True, 7),
                    C("int_8", "Termination", "Either party may terminate with [X] days' notice.", True, 8),
                ],
            },
        ],
    },

    # ── 4. Property & Lease ──
    {
        "name": "Property & Lease",
        "description": "Agreements for rental, leasing, and property transactions",
        "icon": "🏠",
        "order": 4,
        "types": [
            {
                "name": "Rent / Lease Agreement",
                "description": "Agreement between landlord and tenant for rental of property under Transfer of Property Act, 1882",
                "icon": "🏘️",
                "template_path": "property_and_lease/Rent_Lease_Agreement.docx",
                "clauses": [
                    C("rent_1", "Parties & Property Description", "This Agreement is between [LANDLORD NAME] ('Lessor') and [TENANT NAME] ('Lessee') for the property situated at [FULL ADDRESS], measuring approximately [AREA] sq. ft.", True, 1),
                    C("rent_2", "Term of Lease", "The lease shall be for a period of [11 months/X years] commencing from [DATE] and ending on [DATE], unless renewed.", True, 2),
                    C("rent_3", "Monthly Rent", "The Lessee shall pay a monthly rent of ₹[AMOUNT], due on or before the [X]th of each month. Rent escalation of [X]% shall apply upon renewal.", True, 3),
                    C("rent_4", "Security Deposit", "The Lessee shall deposit ₹[AMOUNT] as security deposit, refundable without interest within [X] days of vacating, after deducting dues if any.", True, 4),
                    C("rent_5", "Permitted Use", "The premises shall be used solely for [residential/commercial] purposes. The Lessee shall not sublet or assign without written consent.", True, 5),
                    C("rent_6", "Maintenance & Repairs", "Minor repairs and maintenance: Lessee's responsibility.\nStructural repairs and major maintenance: Lessor's responsibility.", True, 6),
                    C("rent_7", "Utilities", "Electricity, water, gas, and internet charges shall be borne by the Lessee. Property tax and society maintenance shall be borne by the Lessor.", True, 7),
                    C("rent_8", "Notice Period", "Either party shall give [X] months' written notice before vacating or requesting vacation.", True, 8),
                    C("rent_9", "Lock-in Period", "A lock-in period of [X] months shall apply, during which neither party may terminate.", False, 9),
                    C("rent_10", "Registration", "If the lease term exceeds 11 months, this Agreement shall be registered under the Registration Act, 1908. Registration charges shall be borne equally / by [PARTY].", False, 10),
                    C("rent_11", "Governing Law", "Governed by the Transfer of Property Act, 1882 and applicable state rent control laws. Courts at [CITY] shall have jurisdiction.", True, 11),
                ],
            },
            {
                "name": "Leave & License Agreement",
                "description": "Agreement granting permission to use property without creating tenancy rights (common in Maharashtra)",
                "icon": "🔑",
                "clauses": [
                    C("ll_1", "Parties & Premises", "This Leave & License Agreement is between [LICENSOR] and [LICENSEE] for premises at [ADDRESS].", True, 1),
                    C("ll_2", "License Period", "The license is granted for [11 months] from [DATE] to [DATE].", True, 2),
                    C("ll_3", "License Fee", "Monthly license fee: ₹[AMOUNT], payable by [DATE] of each month.", True, 3),
                    C("ll_4", "Deposit", "Refundable deposit of ₹[AMOUNT]. No interest on deposit.", True, 4),
                    C("ll_5", "Purpose", "The premises shall be used only for [residential/commercial] purposes.", True, 5),
                    C("ll_6", "No Tenancy Rights", "This is a Leave & License arrangement and shall not create any tenancy rights under the Maharashtra Rent Control Act or any applicable rent control legislation.", True, 6),
                    C("ll_7", "Maintenance", "Day-to-day maintenance by Licensee. Structural repairs by Licensor.", True, 7),
                    C("ll_8", "Termination", "Either party may terminate with [X] month notice. Licensee shall vacate and hand over peaceful possession.", True, 8),
                    C("ll_9", "Registration", "This agreement shall be registered as required under the Maharashtra Rent Control Act / applicable state laws.", True, 9),
                ],
            },
            {
                "name": "LLP Agreement",
                "description": "Agreement for forming a Limited Liability Partnership (LLP) in India",
                "icon": "🤝",
                "template_fields": [
                    {"name": "llp_name", "type": "text", "label": "LLP Name (e.g., ABC LLP)", "required": True},
                    {"name": "execution_date", "type": "text", "label": "Date of Execution (e.g., 20th January 2026)", "required": True},
                    {"name": "effective_date", "type": "text", "label": "Effective Date (e.g., 01.01.2026)", "required": True},
                    {"name": "execution_place", "type": "text", "label": "Place of Execution", "required": True},
                    {"name": "partner_1_name", "type": "text", "label": "Partner 1 Name", "required": True},
                    {"name": "partner_1_father", "type": "text", "label": "Partner 1 Father's Name", "required": True},
                    {"name": "partner_1_address", "type": "textarea", "label": "Partner 1 Address", "required": True},
                    {"name": "partner_2_name", "type": "text", "label": "Partner 2 Name", "required": True},
                    {"name": "partner_2_father", "type": "text", "label": "Partner 2 Father's Name", "required": True},
                    {"name": "partner_2_address", "type": "textarea", "label": "Partner 2 Address", "required": True},
                    {"name": "partner_3_name", "type": "text", "label": "Partner 3 Name", "required": False},
                    {"name": "partner_3_father", "type": "text", "label": "Partner 3 Father's Name", "required": False},
                    {"name": "partner_3_address", "type": "textarea", "label": "Partner 3 Address", "required": False},
                    {"name": "llp_name_repeat", "type": "text", "label": "LLP Name (Again)", "required": True},
                    {"name": "llp_id", "type": "text", "label": "LLPIN (if incorporated) or Leave Blank", "required": False},
                    {"name": "llp_business_desc", "type": "textarea", "label": "Main Business Activity Description", "required": True},
                    {"name": "llp_name_repeat_2", "type": "text", "label": "LLP Name (Again)", "required": True},
                    {"name": "llp_registered_office", "type": "textarea", "label": "LLP Registered Office Address", "required": True},
                    {"name": "signature_year", "type": "text", "label": "Year for Signature (e.g., 2026)", "required": True},
                    {"name": "signature_place", "type": "text", "label": "Place of Signature", "required": True},
                ],
                "clauses": [
                    C("llp_1", "Formation of LLP", "The parties agree to form a Limited Liability Partnership (LLP) under the Limited Liability Partnership Act, 2008, with the name [LLP NAME].", True, 1),
                    C("llp_2", "Name and Registered Office", "The name of the LLP shall be [LLP NAME] and its registered office shall be at [REGISTERED OFFICE ADDRESS].", True, 2),
                    C("llp_3", "Business of LLP", "The business of the LLP shall be [DESCRIBE BUSINESS ACTIVITIES].", True, 3),
                    C("llp_4", "Partners and Contribution", "The partners of the LLP shall be [PARTNER 1 NAME], [PARTNER 2 NAME], etc. Each partner shall contribute [AMOUNT] as capital.", True, 4),
                    C("llp_5", "Profit and Loss Sharing", "Profits and losses of the LLP shall be shared among the partners in the ratio of [RATIO].", True, 5),
                    C("llp_6", "Management and Designated Partners", "The management of the LLP shall be vested in the Designated Partners. [DESIGNATED PARTNER 1 NAME] and [DESIGNATED PARTNER 2 NAME] shall be the Designated Partners.", True, 6),
                    C("llp_7", "Rights and Duties of Partners", "Each partner shall have the rights and duties as specified in this Agreement and the LLP Act, 2008.", True, 7),
                    C("llp_8", "Bank Account", "A bank account shall be opened in the name of the LLP, and all transactions shall be conducted through this account.", True, 8),
                    C("llp_9", "Admission of New Partner", "A new partner may be admitted with the consent of all existing partners and by amending this Agreement.", True, 9),
                    C("llp_10", "Cessation of Partner", "A partner may cease to be a partner by giving [X] days' notice or as per the provisions of the LLP Act, 2008.", True, 10),
                    C("llp_11", "Dissolution of LLP", "The LLP may be dissolved as per the provisions of the LLP Act, 2008.", True, 11),
                    C("llp_12", "Arbitration", "Any dispute or difference arising between the partners concerning the LLP shall be referred to arbitration under the Arbitration and Conciliation Act, 1996.", True, 12),
                    C("llp_13", "Governing Law", "This Agreement shall be governed by and construed in accordance with the laws of India and the Limited Liability Partnership Act, 2008.", True, 13),
                ]
            },
            {
                "name": "Sale Agreement (Property)",
                "description": "Agreement for sale of immovable property",
                "icon": "🏗️",
                "clauses": [
                    C("sale_1", "Parties", "This Agreement to Sell is between [SELLER] ('Vendor') and [BUYER] ('Purchaser').", True, 1),
                    C("sale_2", "Description of Property", "The property described as [FULL LEGAL DESCRIPTION] bearing Survey/Plot No. [NUMBER], situated at [ADDRESS], measuring [AREA].", True, 2),
                    C("sale_3", "Sale Consideration", "Total sale price: ₹[AMOUNT] (Rupees [IN WORDS] only).\nPayment schedule:\n- Token/Earnest Money: ₹[AMOUNT] on execution\n- Balance: ₹[AMOUNT] on or before registration", True, 3),
                    C("sale_4", "Title & Encumbrance", "The Vendor represents that the property has a clear and marketable title, free from all encumbrances, liens, charges, and litigation.", True, 4),
                    C("sale_5", "Completion Timeline", "The sale deed shall be executed and registered within [X] days from the date of this Agreement.", True, 5),
                    C("sale_6", "Stamp Duty & Registration", "Stamp duty and registration charges shall be borne by the Purchaser. The Vendor shall provide all original title documents.", True, 6),
                    C("sale_7", "Possession", "Vacant and peaceful possession shall be delivered on the date of registration / within [X] days of registration.", True, 7),
                    C("sale_8", "Default", "If the Vendor defaults, the earnest money shall be refunded with [X]% penalty. If the Purchaser defaults, the earnest money shall be forfeited.", True, 8),
                    C("sale_9", "Representations & Warranties", "The Vendor warrants that all taxes, dues, and society charges are paid up to date.", True, 9),
                    C("sale_10", "Jurisdiction", "Courts at [CITY] shall have exclusive jurisdiction.", True, 10),
                ],
            },
            {
                "name": "Sub-Lease Agreement",
                "description": "Agreement to sub-let leased premises to a third party with landlord consent",
                "icon": "🔄",
                "clauses": [
                    C("sub_1", "Parties", "Between [ORIGINAL LESSEE] ('Sub-Lessor') and [SUB-LESSEE], with the consent of [ORIGINAL LESSOR/LANDLORD].", True, 1),
                    C("sub_2", "Consent of Landlord", "The original Landlord has granted written consent for this sub-lease (attached as Annexure).", True, 2),
                    C("sub_3", "Premises", "The sub-leased premises comprise [DESCRIBE PORTION] of the property at [ADDRESS].", True, 3),
                    C("sub_4", "Term", "Sub-lease term: [X] months from [DATE], not exceeding the original lease term.", True, 4),
                    C("sub_5", "Rent", "Monthly sub-lease rent: ₹[AMOUNT].", True, 5),
                    C("sub_6", "Terms of Original Lease", "The Sub-Lessee shall comply with all terms of the original lease agreement.", True, 6),
                    C("sub_7", "Termination", "This sub-lease automatically terminates upon termination of the original lease.", True, 7),
                ],
            },
            {
                "name": "Tenancy Agreement",
                "description": "Formal tenancy agreement with notice and eviction provisions",
                "icon": "🏡",
                "clauses": [
                    C("ten_1", "Parties & Premises", "Between [LANDLORD] and [TENANT] for the premises at [ADDRESS].", True, 1),
                    C("ten_2", "Tenancy Period", "The tenancy shall be for [X] years commencing [DATE].", True, 2),
                    C("ten_3", "Rent & Escalation", "Monthly rent: ₹[AMOUNT] with annual escalation of [X]%.", True, 3),
                    C("ten_4", "Security Deposit", "Security deposit of ₹[AMOUNT], refundable on vacating after adjustments.", True, 4),
                    C("ten_5", "Use of Premises", "For [residential/commercial] use only. No illegal activities permitted.", True, 5),
                    C("ten_6", "Maintenance", "Tenant responsible for internal maintenance. Landlord responsible for structural integrity.", True, 6),
                    C("ten_7", "Eviction", "Eviction permissible under grounds specified in applicable Rent Control legislation.", True, 7),
                    C("ten_8", "Notice", "[X] months' written notice required for termination.", True, 8),
                    C("ten_9", "Stamp Duty", "Stamp duty as per applicable state law shall be borne by [PARTY].", True, 9),
                ],
            },
        ],
    },

    # ── 5. Financial & Lending ──
    {
        "name": "Financial & Lending",
        "description": "Agreements for loans, mortgages, investments, and financial instruments",
        "icon": "💰",
        "order": 5,
        "types": [
            {
                "name": "Loan Agreement",
                "description": "Agreement between lender and borrower for a loan facility",
                "icon": "🏦",
                "clauses": [
                    C("loan_1", "Parties", "This Loan Agreement is between [LENDER] and [BORROWER].", True, 1),
                    C("loan_2", "Loan Amount & Disbursement", "The Lender agrees to lend ₹[AMOUNT] (Rupees [IN WORDS]). Disbursement shall be via [bank transfer/cheque] to [ACCOUNT DETAILS].", True, 2),
                    C("loan_3", "Purpose of Loan", "The loan shall be utilized solely for [STATED PURPOSE]. Diversion of funds constitutes default.", True, 3),
                    C("loan_4", "Interest Rate", "Interest at [X]% per annum, [simple/compounding monthly]. Interest shall be computed on reducing balance.", True, 4),
                    C("loan_5", "Repayment Schedule", "The loan shall be repaid in [X] equal monthly instalments of ₹[AMOUNT] each, commencing from [DATE].", True, 5),
                    C("loan_6", "Prepayment", "The Borrower may prepay the loan in full or in part with [X] days' notice. Prepayment penalty of [X]% shall apply / No prepayment penalty.", False, 6),
                    C("loan_7", "Security/Collateral", "The loan is secured by [DESCRIBE SECURITY — property/FD/shares]. The Borrower shall execute all necessary security documents.", False, 7),
                    C("loan_8", "Events of Default", "Default includes: non-payment, misrepresentation, insolvency, breach of covenants. Upon default, the entire outstanding becomes immediately payable.", True, 8),
                    C("loan_9", "Representations by Borrower", "The Borrower represents that: (a) they have legal capacity; (b) no pending litigation affecting ability to repay; (c) financial statements provided are true and correct.", True, 9),
                    C("loan_10", "Stamp Duty", "Stamp duty as applicable under the Indian Stamp Act shall be borne by the Borrower.", True, 10),
                    C("loan_11", "Governing Law", "Governed by Indian law. Courts at [CITY] shall have jurisdiction. TDS provisions under Section 194A of the Income Tax Act shall apply.", True, 11),
                ],
            },
            {
                "name": "Investment Agreement",
                "description": "Agreement for equity/debt investment into a company",
                "icon": "📈",
                "clauses": [
                    C("inv_1", "Parties", "Between [INVESTOR] and [COMPANY], incorporated under the Companies Act, 2013.", True, 1),
                    C("inv_2", "Investment Amount & Instrument", "The Investor shall invest ₹[AMOUNT] by way of [equity shares/CCDs/CCPs] in the Company.", True, 2),
                    C("inv_3", "Valuation", "Pre-money valuation: ₹[AMOUNT]. Post-money valuation: ₹[AMOUNT]. Price per share: ₹[AMOUNT].", True, 3),
                    C("inv_4", "Conditions Precedent", "Investment is contingent upon:\n- Satisfactory due diligence\n- Board and shareholder approvals\n- Execution of SHA/SSA\n- Compliance with FEMA (if applicable)", True, 4),
                    C("inv_5", "Representations & Warranties", "The Company warrants compliance with all applicable laws, accuracy of financials, and no undisclosed liabilities.", True, 5),
                    C("inv_6", "Board Representation", "The Investor shall have the right to nominate [X] director(s) to the Board.", True, 6),
                    C("inv_7", "Anti-Dilution", "Full ratchet / weighted average anti-dilution protection on down-rounds.", False, 7),
                    C("inv_8", "Information Rights", "The Company shall provide monthly/quarterly financial statements and annual audited accounts.", True, 8),
                    C("inv_9", "Exit Mechanism", "The Investor may exit via IPO, strategic sale, or buyback within [X] years.", True, 9),
                    C("inv_10", "Governing Law", "Governed by Indian law. FEMA/RBI regulations shall be complied with for foreign investments.", True, 10),
                ],
            },
            {
                "name": "Guarantee Agreement",
                "description": "Agreement by a guarantor to secure obligations of a borrower",
                "icon": "🛡️",
                "clauses": [
                    C("gua_1", "Parties", "Between [LENDER/CREDITOR], [BORROWER/PRINCIPAL DEBTOR] and [GUARANTOR].", True, 1),
                    C("gua_2", "Guarantee", "The Guarantor unconditionally and irrevocably guarantees payment of all amounts owed by the Borrower under [REFERENCE LOAN AGREEMENT].", True, 2),
                    C("gua_3", "Extent of Guarantee", "This guarantee covers the principal amount of ₹[AMOUNT], interest, costs, and all charges.", True, 3),
                    C("gua_4", "Nature of Guarantee", "This is a continuing guarantee as defined under Section 129 of the Indian Contract Act, 1872, and shall not be revoked without the Lender's written consent.", True, 4),
                    C("gua_5", "Demand on Guarantor", "The Lender may demand payment from the Guarantor without first proceeding against the Borrower.", True, 5),
                    C("gua_6", "Rights of Guarantor", "Upon payment, the Guarantor shall be subrogated to all rights of the Lender against the Borrower as per Section 140 of the Indian Contract Act.", True, 6),
                    C("gua_7", "Stamp Duty", "Stamp duty shall be borne by the Guarantor.", True, 7),
                ],
            },
            {
                "name": "Mortgage Deed",
                "description": "Agreement creating a mortgage over immovable property as security",
                "icon": "🏛️",
                "clauses": [
                    C("mort_1", "Parties", "Between [MORTGAGOR] and [MORTGAGEE].", True, 1),
                    C("mort_2", "Property Description", "The Mortgagor mortgages the property at [ADDRESS], Survey No. [NUMBER], measuring [AREA].", True, 2),
                    C("mort_3", "Secured Obligation", "This mortgage secures the loan of ₹[AMOUNT] granted under [LOAN AGREEMENT] dated [DATE].", True, 3),
                    C("mort_4", "Type of Mortgage", "This is a [Simple Mortgage/English Mortgage/Mortgage by Deposit of Title Deeds] as per Section 58 of the Transfer of Property Act, 1882.", True, 4),
                    C("mort_5", "Covenants of Mortgagor", "The Mortgagor shall: maintain the property, pay all taxes, not create further charges without consent, and keep the property insured.", True, 5),
                    C("mort_6", "Enforcement", "On default, the Mortgagee may enforce the mortgage under SARFAESI Act, 2002 (if applicable) or through court.", True, 6),
                    C("mort_7", "Release", "Upon full repayment, the Mortgagee shall execute a release deed and return all title documents.", True, 7),
                    C("mort_8", "Registration", "This mortgage deed shall be registered under the Registration Act, 1908.", True, 8),
                ],
            },
            {
                "name": "Hypothecation Agreement",
                "description": "Agreement pledging movable assets as security without transfer of possession",
                "icon": "🚗",
                "clauses": [
                    C("hyp_1", "Parties", "Between [BORROWER/HYPOTHECATOR] and [LENDER].", True, 1),
                    C("hyp_2", "Hypothecated Assets", "The Borrower hypothecates the following movable assets:\n[LIST OF ASSETS WITH DETAILS — vehicles, machinery, inventory, etc.]", True, 2),
                    C("hyp_3", "Secured Obligation", "This hypothecation secures the loan of ₹[AMOUNT].", True, 3),
                    C("hyp_4", "Possession & Use", "The Borrower retains possession and may use the assets in the ordinary course of business.", True, 4),
                    C("hyp_5", "Insurance", "Assets shall be insured at Borrower's cost with the Lender as loss payee.", True, 5),
                    C("hyp_6", "Default & Seizure", "On default, the Lender may seize and sell the hypothecated assets after due notice.", True, 6),
                    C("hyp_7", "CERSAI Registration", "The hypothecation shall be registered with CERSAI as per the Securitisation Act.", True, 7),
                ],
            },
        ],
    },

    # ── 6. Vendor & Procurement ──
    {
        "name": "Vendor & Procurement",
        "description": "Agreements for vendor relationships, supply chains, and distribution",
        "icon": "🚚",
        "order": 6,
        "types": [
            {
                "name": "Vendor Agreement",
                "description": "Agreement between a company and its vendor/supplier",
                "icon": "🏪",
                "clauses": [
                    C("ven_1", "Parties & Engagement", "This Agreement is between [COMPANY] ('Buyer') and [VENDOR] ('Seller').", True, 1),
                    C("ven_2", "Goods/Services", "The Vendor shall supply [DESCRIBE GOODS/SERVICES] as per specifications in Schedule A.", True, 2),
                    C("ven_3", "Pricing & Payment", "Prices as per agreed rate card (Annexure). GST extra. Payment within [X] days of invoice. TDS as applicable.", True, 3),
                    C("ven_4", "Delivery Terms", "Delivery at [LOCATION]. Delivery schedule as per purchase orders. Risk passes on delivery.", True, 4),
                    C("ven_5", "Quality Standards", "Goods/services shall meet [QUALITY STANDARDS/ISO/BIS]. Buyer may inspect and reject non-conforming goods.", True, 5),
                    C("ven_6", "Warranty", "Vendor warrants goods against defects for [X] months from delivery. Defective goods shall be replaced at Vendor's cost.", True, 6),
                    C("ven_7", "Indemnification", "Vendor indemnifies Buyer against claims arising from defective goods, IP infringement, or non-compliance.", True, 7),
                    C("ven_8", "Confidentiality", "Both parties shall protect each other's confidential information.", True, 8),
                    C("ven_9", "Termination", "[X] days' written notice. Immediate for material breach. Outstanding POs shall be fulfilled.", True, 9),
                    C("ven_10", "Governing Law", "Indian law. Courts at [CITY].", True, 10),
                ],
            },
            {
                "name": "Supply Agreement",
                "description": "Long-term agreement for regular supply of goods or materials",
                "icon": "📦",
                "clauses": [
                    C("sup_1", "Parties", "Between [SUPPLIER] and [BUYER].", True, 1),
                    C("sup_2", "Products", "Supplier shall supply [PRODUCTS] as per specifications.", True, 2),
                    C("sup_3", "Minimum Order Quantity", "MOQ: [X] units per [month/quarter]. Volume discounts apply above [X] units.", True, 3),
                    C("sup_4", "Pricing", "Fixed pricing for [X] months. Revision with [X] days' advance notice.", True, 4),
                    C("sup_5", "Delivery & Logistics", "Delivery [Ex-works/CIF/FOB] at [LOCATION]. Lead time: [X] days from PO.", True, 5),
                    C("sup_6", "Quality & Inspection", "Supplier guarantees compliance with specifications. Buyer may conduct quality audits.", True, 6),
                    C("sup_7", "Force Majeure", "Excuses performance for events beyond control with prompt notification.", False, 7),
                    C("sup_8", "Term", "[X] years with auto-renewal unless [X] days' notice.", True, 8),
                ],
            },
            {
                "name": "Distribution Agreement",
                "description": "Agreement appointing a distributor for products in a territory",
                "icon": "🌐",
                "clauses": [
                    C("dist_1", "Appointment", "The Company appoints [DISTRIBUTOR] as its authorized distributor for [PRODUCTS] in [TERRITORY].", True, 1),
                    C("dist_2", "Territory & Exclusivity", "Territory: [DEFINE]. This appointment is [exclusive/non-exclusive].", True, 2),
                    C("dist_3", "Minimum Purchase Commitment", "Distributor shall purchase minimum ₹[AMOUNT] of Products per [quarter/year].", True, 3),
                    C("dist_4", "Pricing & Margins", "Products supplied at [X]% discount to MRP. Distributor shall not sell below [MINIMUM PRICE].", True, 4),
                    C("dist_5", "Marketing & Branding", "Distributor shall promote Products per Company's brand guidelines and contribute [X]% to marketing.", False, 5),
                    C("dist_6", "Returns & Damaged Goods", "Defective goods returnable within [X] days. Credit note issued upon verification.", True, 6),
                    C("dist_7", "IP & Branding", "Company's trademarks and IP shall be used only for authorized distribution.", True, 7),
                    C("dist_8", "Termination", "[X] months' notice for convenience. Immediate for breach or failure to meet minimums.", True, 8),
                    C("dist_9", "Post-Termination", "Distributor may sell remaining inventory for [X] days. Thereafter no use of Company branding.", True, 9),
                ],
            },
            {
                "name": "Agency Agreement",
                "description": "Agreement appointing an agent to act on behalf of the principal",
                "icon": "🤝",
                "clauses": [
                    C("agen_1", "Appointment", "The Principal appoints [AGENT] as its agent for [PURPOSE] in [TERRITORY].", True, 1),
                    C("agen_2", "Authority", "The Agent is authorized to [DESCRIBE PERMITTED ACTIVITIES]. The Agent shall not exceed the scope of authority.", True, 2),
                    C("agen_3", "Commission", "Commission of [X]% on [net invoice value/gross sales]. Payable [monthly/quarterly] after receipt of payment.", True, 3),
                    C("agen_4", "Duties of Agent", "The Agent shall:\n- Act in good faith and in Principal's best interest\n- Maintain proper records and accounts\n- Remit collections promptly\n- Comply with all applicable laws", True, 4),
                    C("agen_5", "Principal's Obligations", "The Principal shall provide necessary support, product information, marketing materials, and timely commission payments.", True, 5),
                    C("agen_6", "Non-Compete", "During the term and [X] months after, Agent shall not represent competing products.", False, 6),
                    C("agen_7", "Term & Termination", "[X] months' notice. Agent liability continues for pending transactions.", True, 7),
                    C("agen_8", "Governing Law", "Indian Contract Act, 1872 (Sections 182-238). Courts at [CITY].", True, 8),
                ],
            },
            {
                "name": "Commission Agreement",
                "description": "Agreement for commission-based sales or referral arrangement",
                "icon": "💵",
                "template_path": "vendor_and_procurement/Commission_Agreement_Template.docx",
                "template_fields": [
                    {"name": "party_a_name", "type": "text", "label": "Company Name", "required": True},
                    {"name": "party_a_address", "type": "textarea", "label": "Company Address", "required": True},
                    {"name": "party_b_name", "type": "text", "label": "Agent Name", "required": True},
                    {"name": "party_b_address", "type": "textarea", "label": "Agent Address", "required": True},
                    {"name": "agent_name", "type": "text", "label": "Agent Name (Again)", "required": True},
                    {"name": "company_name", "type": "text", "label": "Company Name (Again)", "required": True},
                    {"name": "territory", "type": "text", "label": "Territory", "required": True},
                    {"name": "client_name", "type": "text", "label": "Main Client Name", "required": True},
                    {"name": "product", "type": "text", "label": "Product", "required": True},
                    {"name": "termination_months", "type": "number", "label": "Termination Notice (Months)", "required": True},
                    {"name": "commission_rate", "type": "text", "label": "Commission Rate (e.g., USD @ 10% PMT)", "required": True},
                    {"name": "effective_date", "type": "date", "label": "Agreement Effective Date", "required": True},
                    {"name": "start_date", "type": "date", "label": "Start Date", "required": True},
                    {"name": "agent_territory", "type": "text", "label": "Agent Territory (e.g., Portugal & Europe)", "required": True},
                    {"name": "arbitration_country", "type": "text", "label": "Arbitration Country", "required": True},
                    {"name": "company_name_signature", "type": "text", "label": "Company Name Signature", "required": True},
                    {"name": "date_signed", "type": "date", "label": "Date Signed", "required": True},
                ],
                "clauses": [
                    C("comm_1", "Parties", "Between [COMPANY] and [COMMISSION AGENT/REFERRER].", True, 1),
                    C("comm_2", "Services", "The Agent shall introduce prospective clients/customers and facilitate sales of [PRODUCTS/SERVICES].", True, 2),
                    C("comm_3", "Commission Structure", "Commission: [X]% of [net invoice value / collected revenue].\n- One-time / Recurring for [X] months\n- Paid within [X] days of Company receiving payment", True, 3),
                    C("comm_4", "Eligible Sales", "Commission payable only on sales directly attributable to Agent's introduction. Company's decision is final.", True, 4),
                    C("comm_5", "Accounting & Disputes", "Company shall provide monthly commission statements. Disputes to be raised within [X] days.", True, 5),
                    C("comm_6", "Independent Contractor", "Agent is not an employee. No employment benefits, PF, or statutory dues apply.", True, 6),
                    C("comm_7", "TDS", "TDS under Section 194H of the Income Tax Act shall be deducted on commission payments.", True, 7),
                    C("comm_8", "Termination", "Either party may terminate with [X] days' notice. Outstanding commissions remain payable.", True, 8),
                ],
            },
        ],
    },
]


async def seed():
    async with AsyncSessionLocal() as db:
        for cat_data in SEED_DATA:
            # Check if category already exists
            from sqlalchemy.future import select
            existing = await db.execute(
                select(AgreementCategory).where(AgreementCategory.name == cat_data["name"])
            )
            if existing.scalars().first():
                print(f"  ⏭️  Category '{cat_data['name']}' already exists, skipping.")
                continue

            cat = AgreementCategory(
                name=cat_data["name"],
                description=cat_data["description"],
                icon=cat_data["icon"],
                display_order=cat_data["order"],
            )
            db.add(cat)
            await db.flush()  # get cat.id

            for i, type_data in enumerate(cat_data["types"]):
                atype = AgreementType(
                    category_id=cat.id,
                    name=type_data["name"],
                    description=type_data["description"],
                    icon=type_data.get("icon", "📄"),
                    display_order=i + 1,
                    default_clauses=type_data["clauses"],
                    template_path=type_data.get("template_path"),
                    template_fields=type_data.get("template_fields"), # Added this line to handle template_fields
                )
                db.add(atype)

            print(f"  ✅ Seeded category: {cat_data['name']} ({len(cat_data['types'])} types)")

        await db.commit()
        print("\n🎉 All agreement data seeded successfully!")


if __name__ == "__main__":
    print("🌱 Seeding Agreement Categories & Types...")
    asyncio.run(seed())
